brn-mongo:
  image: mongo:3.2
  container_name: brn-mongo
  restart: always
  ports:
  - "27017:27017"
  log_opt:
    max-size: "1m"
    max-file: "3"
  volumes:
  - /data/db
  environment:
  - NODE_ENV=devel
  

brn-nginx:
  image: brn-nginx
  container_name: brn-nginx
  restart: always
  extra_hosts:
  - "DOCKER_HOST_IP:192.168.0.101"
  ports:
  - "443:443"
  - "80:80"
  log_opt:
    max-size: "1m"
    max-file: "3"