export const NOTIFY_AJAX_CALL = 'NOTIFY_AJAX_CALL';
export const NOTIFY_AJAX_CALL_FAILURE = 'NOTIFY_AJAX_CALL_FAILURE';
export const NOTIFY_AJAX_CALL_SUCCESS = 'NOTIFY_AJAX_CALL_SUCCESS';

export const LOAD_BACKBONE_USECASE_SUCCESS = 'LOAD_BACKBONE_USECASE_SUCCESS';
export const LOAD_BACKBONE_USECASE_FAILURE = 'LOAD_BACKBONE_USECASE_FAILURE';


export const NOTIFY_APPLICATION_USER = 'NOTIFY_APPLICATION_USER';
